EXECUTE SP_RESET_SEQUENCE('SQ_ALUNO');
EXECUTE SP_RESET_SEQUENCE('SQ_CURSO');
EXECUTE SP_RESET_SEQUENCE('SQ_CURSO_MATERIA');
EXECUTE SP_RESET_SEQUENCE('SQ_GRADE');
EXECUTE SP_RESET_SEQUENCE('SQ_MATERIA');