CREATE OR REPLACE VIEW VW_CURSO_MATERIA
AS
SELECT  CURSO.ID AS CURSOID, 
        CURSO.NOME AS CURSONOME, 
        MATERIA.ID AS MATERIAID,         
        MATERIA.NOME AS MATERIANOME, 
        MATERIA.DESCRICAO AS MATERIADESCRICAO
FROM CURSO_MATERIA
    INNER JOIN CURSO ON CURSO.ID = CURSO_MATERIA.CURSO_ID
    INNER JOIN MATERIA ON MATERIA.ID = CURSO_MATERIA.MATERIA_ID;