CREATE OR REPLACE VIEW VW_CURSO_MATERIA
AS
SELECT  CURSO.ID AS CURSO_ID, 
        CURSO.NOME AS NOME_CURSO, 
        MATERIA.ID AS MATERIA_ID,         
        MATERIA.NOME AS NOME_MATERIA, 
        MATERIA.DESCRICAO AS DESCRICAO_MATERIA
FROM CURSO_MATERIA
    INNER JOIN CURSO ON CURSO.ID = CURSO_MATERIA.CURSO_ID
    INNER JOIN MATERIA ON MATERIA.ID = CURSO_MATERIA.MATERIA_ID;