CREATE OR REPLACE VIEW VW_GRADE
AS
SELECT  GRADE.ID AS ID,
        GRADE.NOME AS GRADENOME,
        CURSO.ID AS CURSOID,
        CURSO.NOME AS CURSONOME,
        MATERIA.ID AS MATERIAID,
        MATERIA.NOME AS MATERIANOME,
        ALUNO.ID AS ALUNOID,
        ALUNO.RA AS ALUNORA,
        ALUNO.NOME AS ALUNONOME
FROM GRADE
    INNER JOIN ALUNO ON GRADE.ALUNO_ID = ALUNO.ID
    INNER JOIN CURSO_MATERIA ON GRADE.CURSO_MATERIA_ID = CURSO_MATERIA.ID    
    INNER JOIN MATERIA ON CURSO_MATERIA.MATERIA_ID = MATERIA.ID
    INNER JOIN CURSO ON CURSO_MATERIA.CURSO_ID = CURSO.ID;
