CREATE OR REPLACE VIEW VW_GRADE
AS
SELECT  GRADE.ID AS ID,
        GRADE.NOME AS GRADENOME,
        CURSO.ID AS CURSOID,
        CURSO.NOME AS CURSONOME,
        MATERIA.ID AS MATERIAID,
        MATERIA.NOME AS MATERIANOME,
        ALUNO.ID AS ALUNOID,
        ALUNO.RA AS ALUNORA,
        ALUNO.NOME AS ALUNONOME
FROM GRADE
    INNER JOIN ALUNO ON GRADE.ALUNO_ID = ALUNO.ID
    INNER JOIN MATERIA_CURSO ON GRADE.MATERIA_CURSO_ID = MATERIA_CURSO.ID    
    INNER JOIN MATERIA ON MATERIA_CURSO.MATERIA_ID = MATERIA.ID
    INNER JOIN CURSO ON MATERIA_CURSO.CURSO_ID = CURSO.ID;
