CREATE OR REPLACE VIEW VW_MATERIA_CURSO
AS
SELECT  CURSO.ID AS CURSOID, 
        CURSO.NOME AS CURSONOME, 
        MATERIA.ID AS MATERIAID,         
        MATERIA.NOME AS MATERIANOME, 
        MATERIA.DESCRICAO AS MATERIADESCRICAO
FROM MATERIA_CURSO
    INNER JOIN CURSO ON CURSO.ID = MATERIA_CURSO.CURSO_ID
    INNER JOIN MATERIA ON MATERIA.ID = MATERIA_CURSO.MATERIA_ID;